-- Database: cronometro_db

-- DROP DATABASE IF EXISTS cronometro_db;

CREATE DATABASE cronometro_db
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;
	
	
CREATE TABLE IF NOT EXISTS time (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    start_date timestamp with time zone   NOT NULL,
	end_date timestamp with time zone   NOT NULL,
    duration DOUBLE PRECISION  NOT NULL
);

CREATE TABLE IF NOT EXISTS mark (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    start_date timestamp with time zone  NOT NULL,
    end_date timestamp with time zone  NOT NULL,
    time_id INTEGER REFERENCES time(id)  NOT NULL
)